version = 0.1
[default.deploy.parameters]
stack_name = "document-summary"
resolve_s3 = true
s3_prefix = "document-summary"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "ProjectName=\"document-summary\" Environment=\"dev\" SNSSubscriptionEmailsAlerts=\"poojau@crimsoncloud.in\""
image_repositories = []
disable_rollback = false

[default.global.parameters]
region = "us-east-1"
