version = 0.1
[default.deploy.parameters]
stack_name = "document-summary"
resolve_s3 = true
s3_prefix = "document-summary"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"document-summary\" Environment=\"dev\" EnableS3Lifecycle=\"Disabled\" S3LifecycleDuration=\"30\" EnableDynamoDBPITR=\"false\" EnableDynamoDBDeleteProtection=\"false\" SNSSubscriptionEmailsAlerts=\"\" SQSMessageRetentionPeriod=\"1209600\" SQSVisibilityTimeout=\"300\" MaxReceiveCount=\"5\" RateLimit=\"100\" BurstLimit=\"200\" QuotaLimit=\"1000\" SummaryGenerationLambdaTimeout=\"300\" SummaryGenerationLambdaMemory=\"1024\" CachePolicyTTLMin=\"0\" CachePolicyTTLDefault=\"86400\" CachePolicyTTLMax=\"31536000\" InitiateOCRFunctionBatchSize=\"5\" GenerateSummaryFunctionBatchSize=\"5\" InitiateOCRFunctionLambdaTimeout=\"60\""
image_repositories = []
disable_rollback = true

[default.global.parameters]
region = "us-east-1"
